apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    kubernetes.io/change-cause: "frontend golang  "
  name: frontend-k8s-hands-on
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: IfNotPresent
        image: luchodocker/k8s-hands-on:v2
        
      

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-hands-on
  labels: 
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      