apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  labels:
    role: myrole
spec:
  containers:
    - name: cpu-dem0
      image: vish/stress
      resources:
        limits:
          cpu: "1"
        requests: 
          cpu: "0.5"
      args: 
      - -cpus
      - "2"