
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev

---
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-limit
  namespace: dev
spec:
  limits:
  - max:
      memory: 512Mi
    min:
      memory: 256Mi
    type: Container