apiVersion: v1
kind: Pod
metadata:
  name: podtest2-yaml
  labels:
    role: myrole
spec:
  containers:
    - name: cont1
      image: python:3.6-alpine
      command: ['sh','-c','echo cont1 > index.htmnl && python -m http.server 8082']
    - name: cont2
      image: python:3.6-alpine
      command: ['sh','-c','echo cont2 > index.htmnl && python -m http.server 8083']