apiVersion: v1
kind: Pod
metadata:
  name: podtest2-yaml
  labels:
    role: myrole
spec:
  containers:
    - name: web
      imagePullPolicy: IfNotPresent
      image: k8s-hands-on
      ports:
        - name: web
          containerPort: 80
          protocol: TCP